### PR TITLE
Add Heavy Hitter to examples master

### PR DESCRIPTION
**Pull request by yo2seol**
Adding the heavy hitter example to master.

### CODE REVIEW

**Comment by antoninbas** [comment]
any reason why this is in examples rather than a SIGCOMM 16 directory?

**Comment by yo2seol** [comment]
Chang specifically asked it to be added to the examples folder.

**Comment by chkim4142** [comment]
In that case, let's create SIGCOMM_2016 and put this under there.

Antonin, by the way, what are your criteria for bucketizing the examples? In other words, how are those in the example directory different from those under SIGCOMM_2015 or other directories?

**Comment by antoninbas** [comment]
Usually I create a new directory when the exercise was proposed in a tutorial at an event. This makes it easy for people who attended the event -or people interested in the event- to lookup the exercise & solution.
The examples directory does not use a tutorial format: they are functional P4 snippets that can be run right away. It's not an exercise.

**Comment by yo2seol** [comment]
Ok, I moved it back to the sigcomm directory.

**Pull request merged**
