### PR TITLE
readme: Update logs path

### PR DESCRIPTION
**Pull request by rst0git**
Since commit https://github.com/p4lang/tutorials/commit/76a9067deaf35cd399ed965aa19997776f72ec55 switch log files are stored in the `logs` subfolder.

### CODE REVIEW

**Review by jafingerhut — APPROVED** [review]
Looks good to me.

**Comment by jafingerhut** [comment]
I will wait 2 days before merging this, in case anyone else wants a chance to review it.  As far as I can tell, these changes are correct.

**Review by jnfoster — APPROVED** [review]
LGTM

**Comment by jafingerhut** [comment]
Given an additional reviewer (Nate), I will go back on my "wait 2 days" statement and merge this now with its 2 approvals.

**Pull request merged**
