### PR TITLE
Create release and development VMs

### PR DESCRIPTION
**Pull request by rst0git**
Install p4c, bmv2, pi and ptf from packages instead of building from source. This allows us to avoid installing all build dependencies and include in the VM only the files necessary to run P4 tutorials.

A shared link to the pre-build VM image with the changes proposed in this pull request is available at:
https://drive.google.com/file/d/1d7bB46aAbc9YxUe2d1UXqrAQ6rr8AfOu/view?usp=sharing

### CODE REVIEW

**Comment by jfingerh** [comment]
What would you (and others interested in this repository) think of copying the files originally in vm-ubuntu-20.04 into a new vm-ubuntu-20.04-from-source directory?  I know your packages are built from the source code, but the scripts that build a VM from the source code do offer the flexibility of picking which version of the source code to build the various p4lang packages from.

**Comment by rst0git** [comment]
Thank you Andy, I also think that the build scripts have been thoroughly tested and are very useful as a reference. However, instead of creating two directories (and duplicating the code), we can use a [multi-machine](https://www.vagrantup.com/docs/multi-machine) Vagrantfile with _release_  and _development_ machine.

I have updated the pull request with the proposed changes, and here are the corresponding VMs:
- [P4 Tutorial Release VM (2.8 GB)](https://drive.google.com/file/d/1vYcQCvaig2t9K3DuDoiIUxXJRgn3wGkg/view?usp=sharing)
- [P4 Tutorial Development VM (7.9 GB)](https://drive.google.com/file/d/1zEMH7ASQ-2ERVzWOl4IAqTbYYvOzOP-J/view?usp=sharing)

A release VM can be created with:
```bash
sudo vagrant up
```
It is smaller in size, takes less time to build (30-45 minutes), and allows users to update the P4 software with `apt upgrade`.
And because it shares the same package repository, it would also be compatible with examples in [P4Pi](https://eng.ox.ac.uk/media/9680/ccr21p4pi.pdf) .

A development VM (that includes all build dependencies) can be created with:
```bash
sudo vagrant up dev
```
This VM not only allows users the flexibility to choose which version of the source code to build, but also to experiment with changes in p4c, bmv2, etc.

**Comment by jafingerhut** [comment]
@rst0git Looks like a viable approach to me.  I will try out both `vagrant up` and `vagrant up dev` with the changes proposed in this PR some time soon-ish, but it might not be for another week or so, with other things going on.  I will report back here with any issues I find in the resulting created VMs.

**Comment by jafingerhut** [comment]
I created a VM using these changes and `vagrant up dev`, and the resulting VM passed all my usual tests, so both it and `vagrant up` option both work well in my testing.  Excellent.

**Review by jafingerhut — APPROVED** [review]
LGTM, and I have tested the VMs created by both the `vagrant up` and `vagrant up dev` commands, and they both pass my usual list of tests.

**Pull request merged**
