### PR TITLE
clean up unused Python imports

### PR DESCRIPTION
**Pull request by rst0git**
This pull request is rebased on top of https://github.com/p4lang/tutorials/pull/453. It removes unused Python imports.
The clean up changes have been auto-generated with:
```
pip3 install isort autoflake
isort -rc -sl .
autoflake --remove-all-unused-imports -i -r .
isort -rc -m 3 .
```

### CODE REVIEW

**Comment by jafingerhut** [comment]
When I look at the changes of this PR, I see all of them, including the ones it is based on top of, which is pages and pages of whitespace changes.

Is there a way I can get Github to show me only the changes since then?

**Comment by rst0git** [comment]
> Is there a way I can get Github to show me only the changes since then?

Yes, I rebased this branch on the master branch and updated the pull request. Alternatively, you can open a specific commit from the pull request and Github would show only the changes included in that commit.

**Review by jafingerhut — APPROVED** [review]
LGTM.  That is, I see nothing obviously wrong.  There is no way I am manually checking that all of these import statement changes are correct or not.  I will leave that to future testing to find if they have gotten messed up :-)

**Comment by rst0git** [comment]
> There is no way I am manually checking that all of these import statement changes are correct or not. I will leave that to future testing to find if they have gotten messed up :-)

Thanks Andy! I tested all exercises with these changes yesterday, but if I missed something I would happy to open a PR with a fix.

**Comment by rst0git** [comment]
> There is no way I am manually checking that all of these import statement changes are correct or not. I will leave that to future testing to find if they have gotten messed up :-)

Thanks Andy! I tested all exercises with these changes yesterday, but if I missed something I would happy to open a PR with a fix.

**Pull request merged**
