### PR TITLE
Added TOC and Vagrantfile description

### PR DESCRIPTION
**Pull request by Abhinavcode13**
- Added a TOC (table of contents) and detailed explanation of Vagrantfile.

### CODE REVIEW

**Review by jafingerhut — COMMENTED** [review]
All of the files in the `vm` directory are stated in its `vm/README.md` to be no longer supported, and there for historical purposes only.  I do not think we need to document them any more than they are now, for that reason.

If you want to add more documentation to vm-ubuntu-20.04/README.md for these kinds of things, that would make sense, at least for another year when Ubuntu 20.04 is end-of-free-support.

**Comment by Abhinavcode13** [comment]
All right, so in this part of the repository, there isn't much important documentation needed?

**Comment by jafingerhut** [comment]
I think it would be a waste of time to improve the documentation for the contents of the directory `vm`, primarily because the first sentence of its README.md says "This directory is still here only for historical reference."

**Comment by Abhinavcode13** [comment]
Since this is a historical reference, I'm closing this issue for now.

**Pull request closed without merging**
