### PR TITLE
Reduce memory requirements for installing p4c by 'vagrant up'

### PR DESCRIPTION
**Pull request by jafingerhut**

### CODE REVIEW

**Comment by jafingerhut** [comment]
I got 2 failures out of 2 attempts trying 'vagrant up' with the latest master version of the tutorials repository as of 2019-Oct-28, both failing due to running out of memory while compiling the p4c source code.  It succeeded with the proposed change, because 1 C++ compiler process at a time uses significantly less memory on the VM than 2.

**Comment by antoninbas** [comment]
I think we should disable the unified build altogether when building the VM to avoid that kind of memory issue. `cmake` needs to be invoked with this option: `-DENABLE_UNIFIED_COMPILATION=OFF`.

**Comment by cc10512** [comment]
If you turn the unified compilation off by default, you avoid the risk automatically (assuming that folks do build their tree before opening a PR), and we can only turn it on for CI where it does seem to give a benefit.

**Comment by antoninbas** [comment]
What happened to this PR: https://github.com/p4lang/p4c/pull/2031 ?

The risk is not too big anyway since the tutorials use a specific version of p4c and not the top-of-tree.

**Comment by jafingerhut** [comment]
2 GB of RAM is plenty of memory, when invoking at most one C++ compiler process at a time.  It is only somewhere around 1.1G or 1.2G of memory per process for the biggest memory runs right now, I believe.  But that is enough for it to fail with 2 GB of RAM and 2 parallel C++ compiler processes.

**Comment by cc10512** [comment]
Re p4lang/p4c#2031: weird behavior. @liujed?

**Comment by liujed** [comment]
p4lang/p4c#2031 has been on the back burner due to perceived lack of urgency. I can push it through later today, though.

**Comment by jafingerhut** [comment]
I do not wish to harm anyone's enthusiasm for improvements to p4c build and test infrastructure -- far from it.

I do wish to point out that I believe that this proposed PR for the tutorials repository is a conservative, useful change, whether any changes are made to p4c's build infrastructure or not.  Without it, 'vagrant up' is at best unreliable, and at worst will fail a large fraction of the time.

**Comment by liujed** [comment]
p4lang/p4c#2031 has been merged. This should make it safe for projects dependent on p4c to disable p4c's unified builds.

**Pull request merged**
