### PR TITLE
P4app restore original host ip addresses

### PR DESCRIPTION
**Pull request by jafingerhut**

### CODE REVIEW

**Comment by jafingerhut** [comment]
@theojepsen FYI

**Comment by theojepsen** [comment]
@jafingerhut LGTM

**Comment by antoninbas** [comment]
@jafingerhut it seems you started from an out-of-date p4app branch because you have conflicts and the main.py files don't have my switch MAC address changes

**Comment by jafingerhut** [comment]
OK, let me close this PR and create another one that is hopefully correct.

**Pull request closed without merging**
