### PR TITLE
enforce priority for tables with optional match_kind key fiels(#455)

### LINKED ISSUE #455: Add requirement that tables with at least one optional match_kind key field must have priority
See https://github.com/p4lang/tutorials/pull/452 for similar changes already made for match_kind ternary and range.  The chnages for match_kind optional should be very similar.

### PR DESCRIPTION
**Pull request by snapdgn**
Hello, I'm fairly new to p4. This is my attempt to fix #455.

Any feedback or suggestions for improvement would be greatly appreciated. :)

Thanks

### CODE REVIEW

**Comment by jafingerhut** [comment]
Thanks for the PR.

In looking at the existing code, notice that there is a variable `match_types_with_priority`, which I believe contains all match kinds that, if present in a key, cause the table entry to require a priority.  I suspect that a different, probably smaller, change than the one you suggest here would be to add the optional match kind to the set/list/whatever `match_types_with_priority`.  Please investigate an alternate approach like that, to see if you can make it work.

**Comment by snapdgn** [comment]
I agree, that would indeed be a much concise solution to this. It was an oversight on my part to overlook the already defined assertion error message. I provided a new one, when they more or less convey the same meaning.

I believe just adding the OPTIONAL field to the `match_types_with_priority` list should suffice in this case.

**Comment by snapdgn** [comment]
hello @jafingerhut , let me know if this looks good, or any further changes are necessary.

**Review by jafingerhut — APPROVED** [review]
LGTM

**Pull request merged**
