### PR TITLE
Add March 2021 VM based on Ubuntu 20.04

### PR DESCRIPTION
**Pull request by jafingerhut**

### CODE REVIEW

**Comment by jafingerhut** [comment]
Note that while several of the files added by this PR are in a new directory named vm-ubuntu-20.04, leaving the files currently in the directory vm unchanged, it _also_ modifies many Python2 files throughout the entire repository to at least partially update them to Python3.  I don't promise that these changes are completely tested or correct.

I also have no idea whether those Python2 -> Python3 changes would work on an Ubuntu 16.04 VM created using the files in the vm directory.  It seems likely to me that they would not work.

There is no urgency to merge these changes into the main branch, if indeed they ever are in their current form.  I wanted to put this PR somewhere that others would know where to find it, and perhaps test it and make additional improvements to it.

**Comment by jafingerhut** [comment]
If someone would like to download an already-built Ubuntu 20.04 VM for Intel/AMD processors, you can download it here: 
https://drive.google.com/drive/folders/18y1JA8eisvt-L4DkcuDCQUTGaQGbEfc3

**Review by rst0git — APPROVED** [review]

**Review by rst0git — APPROVED** [review]
LGTM

**Comment by rst0git** [comment]
@jnfoster @antoninbas would you be able to review this pull request?

**Review by jnfoster — APPROVED** [review]

**Comment by jafingerhut** [comment]
So I can merge this PR since folks have approved it.  I just want you to realize that with all of the changes to the Python code to go from Python2 to Python3, the Ubuntu 16.04 VM that can be built by the scripts in the 'vm' directory will no longer be able to run the exercises any longer.  I think that is OK, given that Ubuntu 16.04 is past its end of (free) support since April 2021.  I can make another PR that updates a few things in the top level README to make them consistent with the recommended way to create a VM, after merging this in.

**Pull request merged**
