### PR TITLE
Update convert.py

### PR DESCRIPTION
**Pull request by hkgb77**
Added encoding/decoding for Ipv6

### CODE REVIEW

**Comment by hkgb77** [comment]
I signed an individual contributor CLA and added the account in it. Still
getting error in pull request. Please suggest.
Best regards
Harpreet

**Comment by hkgb77** [comment]
I signed an individual contributor CLA and added the account in it. Still getting error in pull request. Please suggest.

**Comment by fruffy** [comment]
> I signed an individual contributor CLA and added the account in it. Still getting error in pull request. Please suggest.

The contributor CLA has an addendum to add your Github name which can be easy to overlook.

**Comment by jafingerhut** [comment]
This is a duplicate of a PR that I just closed a minute ago, because some other PR has made these changes.

**Pull request closed without merging**
