### PR TITLE
Update the description of the tutorials

### PR DESCRIPTION
**Pull request by SadeekFarhan21**
### What
Added description for the tutorials for understanding in one-place.

### Why
The added description would allow the beginners to navigate through the tutorials easily, and they could navigate to their necessary tutorial without having to read the README for that specific tutorial.

### How
This updated markdown includes information about each of the tutorials.

### CODE REVIEW

**Comment by jafingerhut** [comment]
The changes look good to me.  @SadeekFarhan21 are you able to electronically sign the ONF CLA?  There should be a link to do so somewhere in this PR when you view it, I believe.

**Comment by SadeekFarhan21** [comment]
Hi @jafingerhut, thanks for the update. I was unable to electronically sign the ONF CLA yesterday. I am trying to do that right now. Hopefully, that works out.

**Comment by jafingerhut** [comment]
@SadeekFarhan21 Sorry, another change to the README was merged in recently.  If you can resolve the conflicts and push those into this PR (or create a new separate PR, if that is easier for you), that would be much appreciated.

**Comment by AdarshRawat1** [comment]
@SadeekFarhan21 since this PR is meant for adding description, you can also include the description for newly added multicast exercise.

```
<br> <small>This exercise involves writing a P4 program to enable a network switch to multicast packets to multiple output ports based on the destination MAC address. 
 It requires the implementation of logic to handle multicast packets, including defining actions for packet forwarding and configuring the control plane to manage packet processing rules. 
Through practical implementation and testing in a Mininet environment, participants learn to enhance network traffic management and efficiency through multicast communication.</small>

```

**Comment by SadeekFarhan21** [comment]
@jafingerhut @AdarshRawat1 I have updated the changes, and the code is now ready for review. I would appreciate it if you review the code before we merge it.

**Review by jafingerhut — APPROVED** [review]
LGTM

**Pull request merged**
